import Style from "./style.module.css";
import PageHeader from "@/app/components/services/PageHeader/PageHeader";
import BrandSection from "@/app/components/home/BrandSection/BrandSection";
import ServiceBanner from "@/app/components/services/ServiceBanner/ServiceBanner";
import ServiceSidebar from "@/app/components/services/ServiceSidebar/ServiceSidebar";
import ClientSlider from "@/app/components/services/ClientSlider/ClientSlider";
import Breadcrumb from "@/app/components/breadcrumbs/breadcrumbs";
import Image from "next/image";
import Link from "next/link";
import FaqSection from "@/app/components/services/faqs/faqs";


export const metadata = {
    title:
        "Outbound Call Center Solutions | Outbound Call Center Services",

    description:
        "At Tech2Globe, we have a step-by-step process for outbound call center services that are designed to ensure your business is always meeting the needs of your customers.",

    keywords: [
        "Inbound Call Center Services",
        "inbound call center solutions",
        "inbound call center outsourcing",
        "inbound call center service provider",
        "outsource inbound call center services",
        "inbound contact center services",
        "Inbound Call Center Price",
        "Inbound Call Center",
    ],

    alternates: {
        canonical: "https://www.tech2globe.com/outbound-call-center-solutions",
    },

    openGraph: {
        title:
            "Outbound Call Center Solutions | Outbound Call Center Services",
        description:
            "At Tech2Globe, we have a step-by-step process for outbound call center services that are designed to ensure your business is always meeting the needs of your customers.",
        url: "https://www.tech2globe.com/outbound-call-center-solutions",
        siteName: "Tech2Globe Web Solutions LLP",
        type: "website",
    },

    twitter: {
        card: "summary",
        title:
            "Outbound Call Center Solutions | Outbound Call Center Services",
        description:
            "At Tech2Globe, we have a step-by-step process for outbound call center services that are designed to ensure your business is always meeting the needs of your customers.",
    },
};

const faqs = [
    {
        id: "One",
        question: "What services does your outbound call center agency offer?",
        answer: `
        Our outbound call center agency offers a variety of services, including lead generation, sales, market research, and appointment setting. We also provide telemarketing services and customer follow-up calls.
      `,
    },
    {
        id: "Two",
        question: "How do you handle call volume during peak periods?",
        answer: `
        We have a flexible staffing model that allows us to increase the number of agents on the floor during peak periods to ensure that we can handle high call volume. In addition, we have advanced call routing and queue management systems in place to minimize wait times for customers.
      `,
    },
    {
        id: "Three",
        question: "How do you ensure the quality of the leads generated by your agents?",
        answer: `
        We use a combination of techniques to ensure that the leads generated by our agents are of high quality. This includes using targeted calling lists, providing training on effective lead generation techniques, and regularly monitoring and evaluating agent performance. We also provide our clients with detailed reports on the leads generated, including information on the contact's name, phone number, email, and company name.
      `,
    },
    {
        id: "Four",
        question: "How do you ensure the security and confidentiality of customer data?",
        answer: `
        We take the security and confidentiality of customer data very seriously. All of our agents are required to sign confidentiality agreements and are trained on data protection best practices. In addition, we have robust data security systems in place to protect against unauthorized access and hacking attempts.
      `,
    },


];

const pageHeaderData = {
    title: "Outbound Call Center Solution",
    backgroundImage: "/images/skyscraper.jpg",
    shortBanner: true
};

const resources = [
    { id: 1, name: "Case Studies", path: "/case-studies" },
    { id: 2, name: "Our Clients", path: "/clients" },
    { id: 3, name: "Testimonial", path: "/testimonial" },
];

const usefulLinks = [
    { id: 4, name: "Inbound Call Center", path: "/inbound-call-center" },
    { id: 5, name: "Outbound Call Center", path: "/outbound-call-center-solutions" },
    { id: 6, name: "Telemarketing Services", path: "/telemarketing-services" },
    { id: 7, name: "Lead Generation Services", path: "/lead-generation-services" },
    { id: 8, name: "Customer Support Services", path: "/customer-support-services" },
    { id: 9, name: "Virtual Assistant Services", path: "/virtual-assistant-services" },
    { id: 10, name: "Call Center Monitoring", path: "/call-center-monitoring" },
    { id: 11, name: "Call Center Consulting Services", path: "/call-center-consulting" },
    { id: 12, name: "Super Agent Services", path: "/super-agent-services" },
];


const sidebarSections = [
    { heading: "Resources", links: resources },
    { heading: "Useful Links", links: usefulLinks },
];

const testimonials = [
    {
        id: 1,
        quote: "/images/services/service-inner/quote-icon.png",
        text: "I have been using Tech2Globe’s Outbound Call Center Solutions for the past year and I have been extremely happy with the results. Their team is professional, efficient, and always goes above and beyond to ensure that my customer's needs are met. The increase in sales and customer satisfaction has been invaluable to my business. I highly recommend Tech2Globe’s Outbound Call Center Solutions to any company looking to improve their customer outreach.",

    },
    {
        id: 2,
        quote: "/images/services/service-inner/quote-icon.png",
        text: "Tech2Globe’s Outbound Call Center Solutions has been a game changer for our business. Their team is knowledgeable and always quick to respond to our needs. The personalized attention and customized approach to outbound calls has resulted in increased lead generation and customer retention for our company.",

    },
    {
        id: 3,
        quote: "/images/services/service-inner/quote-icon.png",
        text: "We have been working with Tech2Globe’s Outbound Call Center Solutions for the past six months and have seen a significant improvement in our sales and customer satisfaction. Their team is professional, reliable, and always goes the extra mile to ensure that our customers have a positive experience. I highly recommend Tech2Globe’s Outbound Call Center Solutions to any company looking to improve their outbound call strategy.",

    },
];


export default function OutboundCallCenterSolutions() {

    const schemaData = {
        "@context": "https://schema.org",
        "@type": "FAQPage",
        "mainEntity": [
            {
                "@type": "Question",
                "name": "What services does your outbound call center agency offer?",
                "acceptedAnswer": {
                    "@type": "Answer",
                    "text": "Our outbound call center agency offers a variety of services, including lead generation, sales, market research, and appointment setting. We also provide telemarketing services and customer follow-up calls."
                }
            },
            {
                "@type": "Question",
                "name": "How do you handle call volume during peak periods?",
                "acceptedAnswer": {
                    "@type": "Answer",
                    "text": "We have a flexible staffing model that allows us to increase the number of agents on the floor during peak periods to ensure that we can handle high call volume. In addition, we have advanced call routing and queue management systems in place to minimize wait times for customers."
                }
            },
            {
                "@type": "Question",
                "name": "How do you ensure the quality of the leads generated by your agents?",
                "acceptedAnswer": {
                    "@type": "Answer",
                    "text": "We use a combination of techniques to ensure that the leads generated by our agents are of high quality. This includes using targeted calling lists, providing training on effective lead generation techniques, and regularly monitoring and evaluating agent performance. We also provide our clients with detailed reports on the leads generated, including information on the contact’s name, phone number, email, and company name."
                }
            },
            {
                "@type": "Question",
                "name": "How do you ensure the security and confidentiality of customer data?",
                "acceptedAnswer": {
                    "@type": "Answer",
                    "text": "We take the security and confidentiality of customer data very seriously. All of our agents are required to sign confidentiality agreements and are trained on data protection best practices. In addition, we have robust data security systems in place to protect against unauthorized access and hacking attempts."
                }
            }
        ]
    };

    return (
        <>
            <script
                type="application/ld+json"
                dangerouslySetInnerHTML={{ __html: JSON.stringify(schemaData) }}
            />
            <PageHeader pageHeaderData={pageHeaderData} />
            <Breadcrumb parentName="Services" pageName="Outbound Call Center Solutions" />
            <BrandSection />
            <section className={Style.PageContent}>
                <div className="container">
                    <div className="row">
                        <div className="col-lg-9 col-md-9 col-sm-12 col-xs-12">
                            <ServiceBanner imageSrc="/images/services/service-inner/outbound-call-center-services.jpg" />
                            <div className={Style.ContentDiv}></div>



                            <div className={Style.ContentDiv}>
                                <h2>Optimizing Your Outgoing Calls To Achieve Optimal Effectiveness</h2>
                                <p>Do you want your outgoing calls to make an impression? There's no better place to be! We're here to help you in creating a powerful and lasting connection with your customers through our outbound call center services.</p>
                                <p>Whether your objective is to increase sales, provide customer service, or promote your business, we can help you with all of it. Our professionals have the experience and resources to accomplish the task correctly. By utilizing the latest technology and industry tools and customized outbound call center services, we'll aid you in establishing an action plan that is suited to your requirements.</p>

                            </div>

                            <div className={Style.ContentDiv}>
                                <h2>Expert Services for Outbound Call Centers</h2>

                                <p className="mb-4">Outbound call center services can provide the knowledge and resources to attain your objectives to boost sales, improve customer service, and remain connected to your clients. These solutions, which range from all-encompassing call tracking and routing systems to lead-generating and appointment-scheduling services, are made to help you maximize every call</p>
                                <p className="mb-4"><strong>Our Outbound Call Center Solutions Provide The Following Services:</strong></p>

                                <div className="col-lg-12 col-md-12 col-sm-12 col-xs-12 d-flex justify-content-start gap-3">
                                    <div className="col-md-2 col-sm-2 col-xs-3 wpb_single_image d-none d-sm-block" style={{ border: '2px dotted #e5e2e2', padding: 10 }}>
                                        <img src="/images/services/service-inner/call-routing-call-center.png" className="img-responsive img-fluid" alt="Call Monitoring" />
                                    </div>
                                    <div className="col-md-10 col-sm-10 col-xs-12 text-left">
                                        <h4 className="text-dark  fw-bold text-decoration-underline">Call Monitoring</h4>
                                        <p className="text-start">Call length metrics, call abandonment rates, and conversion rates form part of our solutions. Businesses can utilize this data to identify patterns and patterns in the performance of their call-outs. Additionally, they can improve their scripts for calls, marketing strategies, sales strategies, as well as customer support by using this information.
                                        </p>
                                    </div>
                                </div>
                                <div className="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                    <hr />
                                </div>
                                <div className="col-lg-12 col-md-12 col-sm-12 col-xs-12 d-flex justify-content-start gap-3">
                                    <div className="col-md-2 col-sm-2 col-xs-3 wpb_single_image d-none d-sm-block" style={{ border: '2px dotted #e5e2e2', padding: 10 }}>
                                        <img src="/images/services/service-inner/call-tracking-call-center.png" className="img-responsive img-fluid" alt="Call Forwarding" />
                                    </div>
                                    <div className="col-md-10 col-sm-10 col-xs-12 text-left">
                                        <h4 className="text-dark  fw-bold text-decoration-underline">Call Forwarding</h4>
                                        <p className="text-start">Call routing lets us send calls to appropriate agents based on the requirements of the caller. For example, if a customer requires assistance with technical issues an agent with technical support training could be reached through the call routing system in a timely manner.
                                        </p>
                                    </div>
                                </div>
                                <div className="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                    <hr />
                                </div>
                                <div className="col-lg-12 col-md-12 col-sm-12 col-xs-12 d-flex justify-content-start gap-3">
                                    <div className="col-md-2 col-sm-2 col-xs-3 wpb_single_image d-none d-sm-block" style={{ border: '2px dotted #e5e2e2', padding: 10 }}>
                                        <img src="/images/services/service-inner/call-recording-call-center.png" className="img-responsive img-fluid" alt="Call Recording" />
                                    </div>
                                    <div className="col-md-10 col-sm-10 col-xs-12 text-left">
                                        <h4 className="text-dark text-decoration-underline fw-bold">Call Recording</h4>
                                        <p className="text-start">We help companies with call recording and storage to allow for future analysis. This is useful to ensure quality (e.g., to identify areas where agents can perform better) fo,r compliance (e.g., to ensure agents adhere to the relevant rules and regulations), or even training (e.g., to instruct novice agents to handle calls effectively).
                                        </p>
                                    </div>

                                </div>
                                <div className="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                    <hr />
                                </div>
                                <div className="col-lg-12 col-md-12 col-sm-12 col-xs-12 d-flex justify-content-start gap-3">
                                    <div className="col-md-2 col-sm-2 col-xs-3 wpb_single_image d-none d-sm-block" style={{ border: '2px dotted #e5e2e2', padding: 10 }}>
                                        <img src="/images/services/service-inner/analytics-tools-call-center.png" className="img-responsive img-fluid" alt="Analytics Tools" />
                                    </div>
                                    <div className="col-md-10 col-sm-10 col-xs-12 text-left">
                                        <h4 className="text-dark text-decoration-underline fw-bold">Analytics Tools</h4>
                                        <p className="text-start">You can get insight into the performance of your outbound call campaigns by using our analytics software. Call volume length, call duration, as well as the satisfaction of customers, are part of this. We can assist you in identifying patterns of consumer behavior in these data to increase the effectiveness of your call-out campaigns.
                                        </p>
                                    </div>

                                </div>
                                <div className="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                    <hr />
                                </div>

                                <div className="col-lg-12 col-md-12 col-sm-12 col-xs-12 d-flex justify-content-start gap-3">
                                    <div className="col-md-2 col-sm-2 col-xs-3 wpb_single_image d-none d-sm-block" style={{ border: '2px dotted #e5e2e2', padding: 10 }}>
                                        <img src="/images/services/service-inner/lead-generation-call-center.png" className="img-responsive img-fluid" alt="Creating and Qualifying Leads" />
                                    </div>
                                    <div className="col-md-10 col-sm-10 col-xs-12 text-left">
                                        <h4 className="text-dark text-decoration-underline fw-bold">Creating and Qualifying Leads</h4>
                                        <p className="text-start">By making contact with clients and gaining knowledge of their requirements and preferences, we aid businesses in the generation and qualification of leads. Thus, you can focus your efforts and identify promising prospects by finding out more about their needs and their interests.
                                        </p>
                                    </div>

                                </div>
                                <hr />
                                <div className="col-lg-12 col-md-12 col-sm-12 col-xs-12 d-flex justify-content-start gap-3">
                                    <div className="col-md-2 col-sm-2 col-xs-3 wpb_single_image d-none d-sm-block" style={{ border: '2px dotted #e5e2e2', padding: 10 }}>
                                        <img src="/images/services/service-inner/appointment-setting-call-center.png" className="img-responsive img-fluid" alt="Scheduling of Appointments" />
                                    </div>
                                    <div className="col-md-10 col-sm-10 col-xs-12 text-left">
                                        <h4 className="text-dark text-decoration-underline fw-bold">Scheduling of Appointments</h4>
                                        <p className="text-start">Our team may help companies in arranging meetings with potential clients or clients. Calling to set up initial meetings, follow-up visits, and other meetings fall under this grouping. Enhance the efficiency of scheduling and reduce time by automatizing the appointment-setting process.
                                        </p>
                                    </div>

                                </div>
                                <hr />
                                <div className="col-lg-12 col-md-12 col-sm-12 col-xs-12 d-flex justify-content-start gap-3">
                                    <div className="col-md-2 col-sm-2 col-xs-3 wpb_single_image d-none d-sm-block" style={{ border: '2px dotted #e5e2e2', padding: 10 }}>
                                        <img src="/images/services/service-inner/customer-surveys-call-center.png" className="img-responsive img-fluid" alt="Client Feedback" />
                                    </div>
                                    <div className="col-md-10 col-sm-10 col-xs-12 text-left">
                                        <h4 className="text-dark text-decoration-underline fw-bold">Client Feedback</h4>
                                        <p className="text-start">We conduct surveys with customers to find out their thoughts and opinions about a variety of issues such as product use and satisfaction of customers. This can include calling customers and conducting surveys by text or email. Businesses can, therefore, learn what their customers' preferences are more effectively and improve their offerings or services using this information.
                                        </p>
                                    </div>

                                </div>
                                <hr />
                            </div>

                            <div className={Style.ContentDiv}>
                                <h2 className="mt-4 mb-2">Our Detailed Procedure For Contact Center Services</h2>
                                <p>Our step-by-step <Link href="/call-centre-services" className="text-decoration-underline fw-normal">call center outbound service</Link> method at Tech2Globe is designed to ensure that your business can always meet the requirements of your customers.</p>


                                <div className="round-circle-container col-md-12 border-bottom pb-2 d-flex justify-content-start align-items-center gap-3">
                                    <div className="col-md-2 coloredRound" style={{ border: '2px dotted #e5e2e2', borderRadius: '50%', width: 80, height: 80, backgroundColor: 'red', padding: '15px 10px 10px 26px' }}>
                                        <h5 className="text-white fs-1" style={{ color: '#fff' }}>1</h5>
                                    </div>
                                    <div className="col-md-10 text-left pt-3">
                                        <h5 className="fw-bold">Establish your Objectives</h5>
                                        <p className="text-start">Make clear your goals and the objectives you'd like to achieve using our call center outbound services.
                                        </p>
                                    </div>
                                </div>
                                <div className="round-circle-container col-md-12 border-bottom pb-2 d-flex justify-content-start align-items-center gap-3">
                                    <div className="col-md-2 coloredRound" style={{ border: '2px dotted #e5e2e2', borderRadius: '50%', width: 80, height: 80, backgroundColor: '#ffc107', padding: '15px 10px 10px 26px' }}>
                                        <h5 className="text-white fs-1" style={{ color: '#fff' }}>2</h5>
                                    </div>
                                    <div className="col-md-10 text-left pt-3">
                                        <h5 className="fw-bold">Determine Your Target Market</h5>
                                        <p className="text-start">To customize our outbound services to the specific needs of your potential customer's requirements, we've got knowledge of the demographics and preferences and purchase preferences.
                                        </p>
                                    </div>
                                </div>
                                <div className="round-circle-container col-md-12 border-bottom pb-2 d-flex justify-content-start align-items-center gap-3">
                                    <div className="col-md-2 coloredRound" style={{ border: '2px dotted #e5e2e2', borderRadius: '50%', width: 80, height: 80, backgroundColor: '#03a9f4', padding: '15px 10px 10px 26px' }}>
                                        <h5 className="text-white fs-1" style={{ color: '#fff' }}>3</h5>
                                    </div>
                                    <div className="col-md-10 text-left pt-3">
                                        <h5 className="fw-bold">Write A Script</h5>
                                        <p className="text-start">Our team drafts an effective script that effectively communicates your message and addresses any objections that could arise during the conversation.
                                        </p>
                                    </div>
                                </div>
                                <div className="round-circle-container col-md-12 border-bottom pb-2 d-flex justify-content-start align-items-center gap-3">
                                    <div className="col-md-2 coloredRound" style={{ border: '2px dotted #e5e2e2', borderRadius: '50%', width: 80, height: 80, backgroundColor: '#607d8b', padding: '15px 10px 10px 26px' }}>
                                        <h5 className="text-white fs-1" style={{ color: '#fff' }}>4</h5>
                                    </div>
                                    <div className="col-md-10 text-left pt-3">
                                        <h5 className="fw-bold">Educate Representatives</h5>
                                        <p className="text-start">Our employees undergo an extensive course covering the procedure, best techniques for customer service as well as handling all sorts of situations.
                                        </p>
                                    </div>
                                </div>
                                <div className="round-circle-container col-md-12 border-bottom pb-2 d-flex justify-content-start align-items-center gap-3">
                                    <div className="col-md-2 coloredRound" style={{ border: '2px dotted #e5e2e2', borderRadius: '50%', width: 80, height: 80, backgroundColor: '#9c27b0', padding: '15px 10px 10px 26px' }}>
                                        <h5 className="text-white fs-1" style={{ color: '#fff' }}>5</h5>
                                    </div>
                                    <div className="col-md-10 text-left pt-3">
                                        <h5 className="fw-bold">Install monitoring and assessment of calls.</h5>
                                        <p className="text-start">We watch and evaluate the agents' calls to ensure they're following the guidelines and providing top-quality customer service.
                                        </p>
                                    </div>
                                </div>
                                <div className="round-circle-container col-md-12 border-bottom pb-2 d-flex justify-content-start align-items-center gap-3">
                                    <div className="col-md-2 coloredRound" style={{ border: '2px dotted #e5e2e2', borderRadius: '50%', width: 80, height: 80, backgroundColor: '#00764e', padding: '15px 10px 10px 26px' }}>
                                        <h5 className="text-white fs-1" style={{ color: '#fff' }}>6</h5>
                                    </div>
                                    <div className="col-md-10 text-left pt-3">
                                        <h5 className="fw-bold">Review and improve</h5>
                                        <p className="text-start">To increase the effectiveness of our call center outbound services, we review and modify the information gathered through call monitoring.
                                        </p>
                                    </div>
                                </div>
                                <div className="round-circle-container col-md-12 border-bottom pb-2 d-flex justify-content-start align-items-center gap-3">
                                    <div className="col-md-2 coloredRound" style={{ border: '2px dotted #e5e2e2', borderRadius: '50%', width: 80, height: 80, backgroundColor: '#091014', padding: '15px 10px 10px 26px' }}>
                                        <h5 className="text-white fs-1" style={{ color: '#fff' }}>7</h5>
                                    </div>
                                    <div className="col-md-10 text-left pt-3">
                                        <h5 className="fw-bold">Stay in contact</h5>
                                        <p className="text-start">We keep in touch with our clients and take their feedback to improve our services in the outbound call center.
                                        </p>
                                    </div>
                                </div>
                                <div className="round-circle-container col-md-12 border-bottom pb-2 d-flex justify-content-start align-items-center gap-3">
                                    <div className="col-md-2 coloredRound" style={{ border: '2px dotted #e5e2e2', borderRadius: '50%', width: 80, height: 80, backgroundColor: '#673ab7', padding: '15px 10px 10px 26px' }}>
                                        <h5 className="text-white fs-1" style={{ color: '#fff' }}>8</h5>
                                    </div>
                                    <div className="col-md-10 text-left pt-3">
                                        <h5 className="fw-bold">Monitor and evaluate the performance</h5>
                                        <p className="text-start">To determine the efficacy of our call center outbound services, we track and evaluate key performance indicators like conversion rates, client satisfaction, and volume of calls.
                                        </p>
                                    </div>
                                </div>
                                <div className="round-circle-container col-md-12 border-bottom pb-2 d-flex justify-content-start align-items-center gap-3">
                                    <div className="col-md-2 coloredRound" style={{ border: '2px dotted #e5e2e2', borderRadius: '50%', width: 80, height: 80, backgroundColor: '#8bc34a', padding: '15px 10px 10px 26px' }}>
                                        <h5 className="text-white fs-1" style={{ color: '#fff' }}>9</h5>
                                    </div>
                                    <div className="col-md-10 text-left pt-3">
                                        <h5 className="fw-bold">Analysis and reporting</h5>
                                        <p className="text-start">We produce reports regularly and analyze the data to identify patterns or trends and potential development opportunities.
                                        </p>
                                    </div>
                                </div>
                                <div className="round-circle-container col-md-12 border-bottom pb-2 d-flex justify-content-start align-items-center gap-3">
                                    <div className="col-md-2 coloredRound" style={{ border: '2px dotted #e5e2e2', borderRadius: '50%', width: 80, height: 80, backgroundColor: '#ff0058', padding: '15px 10px 10px 26px' }}>
                                        <h5 className="text-white fs-1" style={{ color: '#fff' }}>10</h5>
                                    </div>
                                    <div className="col-md-10 text-left pt-3">
                                        <h5 className="fw-bold">Ensuring quality</h5>
                                        <p className="text-start">We review the performance of our agents on an everyday basis and give them feedback to help them get better.
                                        </p>
                                    </div>
                                </div>
                            </div>

                            <div className={Style.ContentDiv}>
                                <h2 className="pt-3 mb-3">Industries We Cater To</h2>

                                <div className="row pb-3">
                                    <div className="col-md-12">
                                        <div className={Style.inner}>
                                            <div className={`${Style.commonInner} inner1`}>
                                                <div className={`${Style.img} mx-auto`}>
                                                    <img src="/images/services/health-care.png" alt />
                                                </div>
                                                <div className={`${Style.title} mx-auto`}>
                                                    Healthcare
                                                </div>
                                            </div>
                                            <div className={`${Style.commonInner} inner2`}>
                                                <div className={`${Style.img} mx-auto`}>
                                                    <img src="/images/services/skin-care-1-1.png" alt />
                                                </div>
                                                <div className={`${Style.title} mx-auto`}>
                                                    Beauty
                                                </div>
                                            </div>
                                            <div className={`${Style.commonInner} inner3`}>
                                                <div className={`${Style.img} mx-auto`}>
                                                    <img src="/images/services/food.png" alt />
                                                </div>
                                                <div className={`${Style.title} mx-auto`}>
                                                    Food
                                                </div>
                                            </div>
                                            <div className={`${Style.commonInner} inner4`}>
                                                <div className={`${Style.img} mx-auto`}>
                                                    <img src="/images/services/home-1-1.png" alt />
                                                </div>
                                                <div className={`${Style.title} mx-auto`}>
                                                    Home & Kitchen
                                                </div>
                                            </div>
                                            <div className={`${Style.commonInner} inner9`}>
                                                <div className={`${Style.img} mx-auto`}>
                                                    <img src="/images/services/sports-1.png" alt />
                                                </div>
                                                <div className={`${Style.title} mx-auto`}>
                                                    Sports
                                                </div>
                                            </div>
                                        </div>
                                        <div className={Style.inner2}>
                                            <div className={`${Style.commonInner} inner5`}>
                                                <div className={`${Style.img} mx-auto`}>
                                                    <img src="/images/services/fashion.png" alt />
                                                </div>
                                                <div className={`${Style.title} mx-auto`}>
                                                    Fashion
                                                </div>
                                            </div>
                                            <div className={`${Style.commonInner} inner6`}>
                                                <div className={`${Style.img} mx-auto`}>
                                                    <img src="/images/services/open-book-1.png" alt />
                                                </div>
                                                <div className={`${Style.title} mx-auto`}>
                                                    Kindle &amp; Books
                                                </div>
                                            </div>
                                            <div className={`${Style.commonInner} inner7`}>
                                                <div className={`${Style.img} mx-auto`}>
                                                    <img src="/images/services/elec.png" alt />
                                                </div>
                                                <div className={`${Style.title} mx-auto`}>
                                                    Electronics
                                                </div>
                                            </div>
                                            <div className={`${Style.commonInner} inner8`}>
                                                <div className={`${Style.img} mx-auto`}>
                                                    <img src="/images/services/software.png" alt />
                                                </div>
                                                <div className={`${Style.title} mx-auto`}>
                                                    Software
                                                </div>
                                            </div>
                                            <div className={`${Style.commonInner} inner10`}>
                                                <div className={`${Style.img} mx-auto`}>
                                                    <img src="/images/services/all-1.png" alt />
                                                </div>
                                                <div className={`${Style.title} mx-auto`}>
                                                    All
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>



                        </div>
                        <div className="col-lg-3 col-md-3 col-sm-12 col-xs-12 ">
                            <div className={Style.StickyTop}>
                                <ServiceSidebar sections={sidebarSections} />
                            </div>
                        </div>
                        <div className="col-lg-12 col-md-12 col-sm-12 col-xs-12 mt-5">
                            <div className={Style.ContentDiv}>
                                <h2 className="pt-3 text-center">The Advantages of
                                Selecting Tech2Globe as Your Outsourced Outbound Call Center Services Provider</h2>
                                <p className="text-center">Here are a few possible advantages of selecting us to handle your incoming call center needs.</p>
                                <div className="row">
                                    <div className="col-lg-6 col-md-6 col-sm-12 col-xs-12 mb-4">
                                        <div className="carditemcall shadow-sm mb-3 h-100">
                                            <div className="text-center">
                                                <Image src="/images/services/service-inner/team-icon.png" width={100} height={100} alt="Proficiency" />
                                            </div>
                                            <div className="context text-center">
                                                <h5>Proficiency</h5>
                                                <p>Selecting Tech2Globe as your outbound call center provider gives you access to a multitude of expertise and experience. Since we have spent years assisting companies just like yours in growing, our team of professionals is well-versed in the ins and outs of developing successful outbound call campaigns.</p>
                                            </div>
                                        </div>

                                    </div>
                                    <div className="col-lg-6 col-md-6 col-sm-12 col-xs-12 mb-4">
                                        <div className="carditemcall shadow-sm mb-3 h-100">
                                            <div className="text-center">
                                                <Image src="/images/services/service-inner/budget.png" width={100} height={100} alt="Effectiveness" />
                                            </div>
                                            <div className="context text-center">
                                                <h5>Effectiveness</h5>
                                                <p>Because time is money, you can be sure that your outbound call campaigns are being managed properly and efficiently when you work with Tech2Globe. With cutting-edge call monitoring and routing technology and efficient appointment scheduling procedures, we have the knowledge and resources to make the most of every call.</p>
                                            </div>
                                        </div>

                                    </div>
                                    <div className="col-lg-6 col-md-6 col-sm-12 col-xs-12 mb-4">
                                        <div className="carditemcall shadow-sm mb-3 h-100">
                                            <div className="text-center">
                                                <Image src="/images/services/service-inner/budget-management.png" width={100} height={100} alt="Personalization" />
                                            </div>
                                            <div className="context text-center">
                                                <h5>Personalization</h5>
                                                <p>We at Tech2Globe are aware that no two companies are the same. For this reason, we provide a selection of adaptable outbound call center services to match the unique requirements of your company. We can help with lead generation, appointment arranging, or any other kind of need you may have.</p>
                                            </div>
                                        </div>

                                    </div>
                                    <div className="col-lg-6 col-md-6 col-sm-12 col-xs-12 mb-4">
                                        <div className="carditemcall shadow-sm mb-3 h-100">
                                            <div className="text-center">
                                                <Image src="/images/services/service-inner/budget-management.png" width={100} height={100} alt="Scalability" />
                                            </div>
                                            <div className="context text-center">
                                                <h5>Scalability</h5>
                                                <p>As your business grows and evolves, so will your outbound call center needs. With Tech2Globe, you can easily scale up or down as needed to meet the changing demands of your business.</p>
                                            </div>
                                        </div>

                                    </div>
                                    <div className="col-lg-6 col-md-6 col-sm-12 col-xs-12 mb-4">
                                        <div className="carditemcall shadow-sm mb-3 h-100">
                                            <div className="text-center">
                                                <Image src="/images/services/service-inner/team-icon.png" width={100} height={100} alt="Cost savings" />
                                            </div>
                                            <div className="context text-center">
                                                <h5>Cost savings</h5>
                                                <p>Choosing an outbound call center company like Tech2Globe can help you save money in a number of ways. With outsource outbound call center services for your outbound call campaigns, you can avoid the need to hire, train, and manage a team of in-house agents.</p>
                                            </div>
                                        </div>

                                    </div>
                                </div>


                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <div className="EmailMarketingTestimonials">
                <ClientSlider testimonials={testimonials} />
            </div>
            <FaqSection faqs={faqs} />

        </>
    )
}