import "bootstrap/dist/css/bootstrap.min.css";
import { Poppins } from "next/font/google";
import "./globals.css";
import BootstrapClient from "./utilities/BootstrapClient";
import LightboxInitializer from "./utilities/LightboxInitializer";
import Header from "./ui/Header/Header";
import Footer from "./ui/Footer/Footer";
import NextTopLoader from "nextjs-toploader";
import ScrollToTop from "./components/ScrollToTop/ScrollToTop";

const poppins = Poppins({ 
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "Tech2Globe",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={poppins.variable}>
      <body>
        <ScrollToTop />
        <NextTopLoader
          color="#c01f29"
          height={3}
          showSpinner={false}
          speed={200}
        />
        <Header />
        {children}
        <LightboxInitializer />
        <BootstrapClient />
        <Footer />
      </body>
    </html>
  );
}
