import "bootstrap/dist/css/bootstrap.min.css";
import { Poppins } from "next/font/google";
import "./globals.css";
import BootstrapClient from "./utilities/BootstrapClient";
import LightboxInitializer from "./utilities/LightboxInitializer";
import Header from "./ui/Header/Header";
import Footer from "./ui/Footer/Footer";
import NextTopLoader from "nextjs-toploader";
import ScrollToTop from "./components/ScrollToTop/ScrollToTop";
import { fixRelativeLinks } from "@/app/utilities/fixRelativeLinks";
import FixLinksWrapper from "@/app/utilities/FixLinksWrapper";
import Script from "next/script";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "Tech2Globe",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={poppins.variable}>
      {/* ✅ ADD THIS BLOCK */}
      <head>
        <base href="/" />

        {/* Google tag (gtag.js) */}
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-R6ZG8XRESL"
          strategy="afterInteractive"
        />

        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());

            gtag('config', 'G-R6ZG8XRESL');
          `}
        </Script>

        <Script
          id="microsoft-clarity"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              (function(c,l,a,r,i,t,y){
                c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
                t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
                y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
              })(window, document, "clarity", "script", "lf01016blp");
            `,
          }}
        />



      </head>

      <body>
        <div className="main-wrapper">
          <Script
            src="https://challenges.cloudflare.com/turnstile/v0/api.js"
            strategy="afterInteractive"

          />
          <FixLinksWrapper />
          {/* <fixRelativeLinks/> */}
          <ScrollToTop />
          <NextTopLoader
            color="#c01f29"
            height={3}
            showSpinner={false}
            speed={200}
          />
          <Header />
          {children}
          <LightboxInitializer />
          <BootstrapClient />
          <Footer />
        </div>
      </body>
    </html>
  );
}
